import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import { COMMENT_NUM } from './(routes)/hi/[time]/comments/[...slug]/constants';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-5">
          {/* Navigator <Link href="/hello">Hello</Link>|<Link href="/hi">Hi</Link> */}
          Navigator <Link href="/hello">Hello</Link>|<Link href="/hi">Hi</Link>|
          <Link href="/shop/123">123</Link>|
          <Link href="/shop/123/456">456</Link> |
          {/* <Link href="/hi/morning/comments/1">moring 1</Link> */}
          {COMMENT_NUM.map((num) => {
            if (1 <= num && num <= 3)
              return (
                <Link key={num} href={`/hi/morning/comments/${num}`}>
                  moring {num}
                </Link>
              );
            if (4 <= num && num <= 6)
              return (
                <Link key={num} href={`/hi/afternoon/comments/${num}`}>
                  afternoon {num}
                </Link>
              );
            if (7 <= num && num <= 9)
              return (
                <Link key={num} href={`/hi/evening/comments/${num}`}>
                  evening {num}
                </Link>
              );
            return <></>;
          })}
        </nav>
        children
        <footer>footer</footer>
      </body>
    </html>
  );
}

// {children}은 기본적으로 밖에 있는 page나 template을 찾아서 넣는다 이 children이 react에서 OUTlet의 역할이라고 생각하면 돼
// layout 파일을 layout 컴포넌트
